### ISSUE TITLE
Refactor Exercise.completionMsg

### ISSUE THREAD

**Issue by cjerdonek** [teorth/QED#12]
Since `Exercise.completionMsg` isn't so much related to a particular exercise (and is only used once), the `Exercise` class could be simplified slightly by removing `Exercise.completionMsg`. Instead, the message could be shown when the number of solved exercises equals one. This is also how `completedAllExercises()` is already handled (and also makes sense from the perspective that this is a UX issue around how to interact with the user when solving exercises).

Another thing that could be done with this is to move the message text to a div in the HTML, following the pattern of moving more of the text from Javascript (code) to the HTML (textual content).

**Comment by teorth** [comment]
This should now be implemented.
