### ISSUE TITLE
Validate index.html

### ISSUE THREAD

**Issue by cjerdonek** [teorth/QED#13]
This HTML validator can be useful for finding HTML typos in index.html, etc:
https://validator.w3.org/

This issue can be used for resolving the various issues that the validator finds. The checkboxes below can be used for recording what the validator finds and what remaining things need to be resolved.

- [x] (warning) Add `lang="en"`
- [x] (error) An ID must not contain whitespace.
- [x] (error) Bad `href` value: Illegal character in path segment

(I just added a few initial checkbox items after using the validator's "direct input" feature.)

**Comment by teorth** [comment]
Hmm, how serious is the id containing whitespace issue?  Right now some of the ids here are using the same string as is used for game output, so removing whitespace would make things a bit less readable.  Not difficult to fix of course by making a separate string for the id, but if it is only a suggestion rather than a must-fix problem then maybe one could leave things as is.

**Comment by siddhartha-gadgil** [comment]
Conventionally hyphens are used in place of whitespaces, and the result is
reasonably readable. One advantage of not using whitespace is one can
cleanly link to a particular Element using #id

**Comment by cjerdonek** [comment]
It seems to be working fine as is, so it doesn't seem to be critically serious. However, I think it would be good if the desire is to have an app that is closer to professional methods, etc. It's customary to have id's without spaces. (And also, yes, it's preferable for id's to be decoupled from the UI.)

Re: hyphens, yes, those can be used. It might be good to standardize on one of `snake_case`, camelCase, or spinal-case for all ID's / attribute values. I guess spinal-case is preferred in the HTML, though it's not ideal if it will also be used as a JS identifier, in which case one would need to use the standard conversion from spinal-case to camelCase when entering JS-land.

**Comment by teorth** [comment]
OK, I addressed all the issues except for the whitespace one and also some unclosed tag issue reported at the very end of the page that I am not sure where it is originating from (I don't know how to match tags in visual studio to see where the problem is coming from).

**Comment by cjerdonek** [comment]
Also, I fixed the closing tag issue here (a missing final div): a127181de6ab426103fcb94122acfcd72cdd9e30
