### ISSUE TITLE
NOT formula context doesn’t unlock in exercise 11.1

### ISSUE THREAD

**Issue by cjquines** [teorth/QED#14]
Reaching exercise 11.1 (through solving exercise 10.1(a)) and clicking `A` from the formula window does not give `NOT(A)` as one of the options.

Tested in Chrome 69 and reproduced in Edge 25.

**Comment by cjerdonek** [comment]
I think I see the issue: https://github.com/teorth/QED/commit/d7e42ccc03d19f977acb8d11037fce99749f1ae3#diff-bde0b004f70c3410a1b8a814291ec60aL184

I will push a fix.

**Comment by cjerdonek** [comment]
Okay, I pushed the fix. I'm not sure if it will "self correct" or not though. Can you see?

**Comment by Voileexperiments** [comment]
@cjquines Can confirm the fix is applied. Just need to click into Ex11.1 again to unlock the law.
