### ISSUE TITLE
Indiscernability does not pattern match `1`

### ISSUE THREAD

**Issue by Voileexperiments** [teorth/QED#17]
e.g I have this:

![image](https://user-images.githubusercontent.com/14909989/44779881-387cd180-abb3-11e8-87ed-22ff19462d1d.png)

If I invoke Indiscernability of identicals from `a = 1` to `(a * b) = (1 * b)`, I should be able to deduce both `(1 * b) = (1 * b)` and `(a * b) = (a * b)` (since `1` is just a term like `a` and `b`). However, only the former is available:

![image](https://user-images.githubusercontent.com/14909989/44779933-54807300-abb3-11e8-967e-d72945ee345c.png)

**Comment by teorth** [comment]
This is as intended.  The law of indiscernability of identicals asserts that if alpha = beta, and P(alpha) is true, then P(beta) is true.  If instead one knows alpha = beta and P(beta), the law does not directly allow one to deduce P(alpha).  Of course, once one has the symmetry of equality, one can also obtain this law.

One possibility would be to create an exercise to generate this alternate form of indiscernability that can then be added to the list of available laws.  One side effect of this though is that the two laws together may generate quite a lot of matches, including some potentially redundant ones.
