### ISSUE TITLE
Add deduction `NOT FALSE` when dragging `FALSE` into an environment

### ISSUE THREAD

**Issue by Voileexperiments** [teorth/QED#19]
Currently we have to manually create `NOT FALSE` from `FALSE` just to put it into an environment. Maybe an option to put `NOT FALSE` into an environment with just `FALSE` can be added separately as a convenience?

**Comment by teorth** [comment]
An alternate version of the FALSE law should now be added (you may need to reload Ex 13.1(a) to trigger it).
