### ISSUE TITLE
Add Prev/Next Exercise button and hotkeys

### ISSUE THREAD

**Issue by Voileexperiments** [teorth/QED#21]
It's more helpful to navigate between exercises by going forward/backward instead of just warping into the first/last unsolved exercise. Warping into the first unsolved exercise becomes unhelpful to improving workflow if there is a dangling unsolved exercise behind, as pressing `n` no longer warps to the next exercise to which I've just solved (which is what I would usually want), but *always* that dangling exercise.

Suggested hotkeys: Ctrl+Left/Right

**Comment by teorth** [comment]
This has now been implemented.  I used < and > for the hotkeys.
