### ISSUE TITLE
Possibility to remove existing items?

### ISSUE THREAD

**Issue by Voileexperiments** [teorth/QED#23]
Sometimes there are just too many intermediate items around and they are cluttering the screen.

Maybe an option to remove (as in, "forget") existing items can be added, like dragging an item to the recycling bin. Of course, this might cause key items to be removed, but then it's a conscious option, and it's always possible to immediate undo/restart the proof anyway so it isn't that much of a big deal.

- Items in the environment window can be removed. Also preferrable to disallow removing initial given terms
- Formula can be removed, but those involving operators can only be removed after predicates and operators window is unlocked (so as to prevent making a proof unsolvable). Alternatively, disallow removing initial give formulas is also possible
- Terms can be removed as long as there are no references of them across all windows

**Comment by teorth** [comment]
Delete functionality has been added.  I decided not to put in any safeguards, given that this is not a feature that casual players would actually use.
