### ISSUE TITLE
Add more variants of laws that are dependent of the order of `AND`/`OR`

### ISSUE THREAD

**Issue by Voileexperiments** [teorth/QED#26]
e.g Ex 9.5(a) and (b), Monotonicity of AND/OR: while `(A AND C) IMPLIES (B AND C)` is good, often I also want a version that deduces `(C AND A) IMPLIES (C AND B)`. Otherwise I'd have to find a way to either invoke a `AND is commutative` or `(A AND B) IFF (B AND A)`, which is inconvenient and actually hard to do as it's very hard to apply deductions to inner pieces under this system (e.g trying to deduce `((NOT (A IMPLIES B)) OR A) IMPLIES ((NOT ((NOT A) OR B)) OR A)` is just a huge pain.)

More examples:
- Ex 8.5: `A IMPLIES (A AND B)`; why not also `A IMPLIES (B AND A)`?
- Ex 10.1(b-e): This should've been weakened to just plain `IMPLIES`: Why I can only make such deductions from an IFF, but not IMPLIES, considering the former is just the two-way version of the latter?
- Ex 11.1, Ex 12.1(a), Ex 12.3(a), Excluded middle: `(NOT A) AND A` is just as valid as `A AND (NOT A)`, I think. No need to restrict the order. (The same goes to excluded middle, with `AND` replaced by `OR`)
- Ex 12.4(a-b)
- Chapter 13: I'm okay with them not offering the variants actually since they're almost never used after this chapter anyway

**Comment by teorth** [comment]
Additional exercises now added.

**Comment by Voileexperiments** [comment]
@teorth By the way, there is a 6 line proof to the new 9.5(c), which utilizes 9.5(b) and an another law.

**Comment by Voileexperiments** [comment]
Another thing: 10.1(a) should have a helper exercise of `Given B, A IFF B: deduce A.`, since that's the point of  `IFF`: it should be invocable from both sides unlike `IMPLIES`.
