### ISSUE TITLE
Bug or feature?: I could get the solution of every exercise without solving it.

### ISSUE THREAD

**Issue by light42** [teorth/QED#33]
If I open QED webpage using emacs eww browser, it automatically spits out the solutions of all the exercises. It's not that pretty looking though, but it's far more easier to edit it than to solve all the exercises.

**Comment by teorth** [comment]
Yes, this is by design; the interactive text is intended for self-study rather than as a classroom test, and so no attempt is made to conceal the solutions for anyone who wishes to look them up after trying the exercises.
