### ISSUE TITLE
Rename home page to index.html

### ISSUE THREAD

**Issue by cjerdonek** [teorth/QED#4]
I'm pretty sure that if the main page is renamed from `QED.html` to `index.html`, then it will be accessible using the simpler and more easily publicized URL `https://teorth.github.io/QED/` (because of how GitHub Pages is configured).

If this is done, it will require updating some links in the blog, etc. However, a simple [HTML redirect](https://stackoverflow.com/a/5411567/262819) page could also be added for people who already have a bookmarks set, etc.

**Comment by teorth** [comment]
Sure, we can do this.  My reasoning for not using index.html originally was so that one could view the directory containing the code (as in http://www.math.ucla.edu/~tao/QED/ ), but I guess the github website does not permit this, so moving the page and making a redirect would be fine.

**Comment by cjerdonek** [comment]
Closed by a975e3fab8074d7046f392693cb40376d6b7f74f.

@teorth Can you set the "URL" for the GitHub project to `https://teorth.github.io/QED/`? This should be under the GitHub project settings next to the project description (the description is currently set to "Repository for the QED interactive text and possible extensions").
