### ISSUE TITLE
Store exercise notes and proof as HTML

### ISSUE THREAD

**Issue by cjerdonek** [teorth/QED#7]
One easier thing that I think would improve the structure and maintainability of the code would be to store the HTML "notes" and "proof" for each exercise as HTML.

Currently, these HTML strings are stored as JS string literals (in [`docs/js/main.js`](https://github.com/teorth/QED/blob/69a298e551191f2790709bc8293686008722c342/docs/js/main.js)), which isn't great for storing "data" and makes it a bit harder to edit and view the HTML. For example:
https://github.com/teorth/QED/blob/2978fc5dcaf21141885fe90fa62b0ad9ef7ba66c/docs/js/main.js#L29-L30

One idea is to store this information in the form of hidden (i.e. not seen when browsing) "data" divs in the main html file.  The structure for each exercise could be something like--

```html
<div id="exercise-3">
<div class="notes">...</div>
<div class="proof">...</div>
</div>
```

Then a `load_exercise_data(exercise, id)` JS function could be defined that populates an `Exercise` object from the HTML document, and this called from within `main.js` for each exercise. Over time, more of the exercise "data" could be transferred to a more structured form (e.g. the "unlocks" and "unlockedBy" information), until perhaps all of each exercise can be populated from data.

**Comment by teorth** [comment]
I like this suggestion.  I managed to quickly write up some code for this and ported the first exercise HTML data over this way.  Already it revealed that there were some typos etc. in the HTML.  Porting the remaining 132 exercises will be a bit tedious but should be done before too long.

**Comment by cjerdonek** [comment]
Great! A few suggestions on this approach:

* Prefix the element id's with `exercise-` since id's should be globally unique within the document, and there could a priori be other types of objects.
* Use [`document.getElementById()`](https://developer.mozilla.org/en-US/docs/Web/API/Document/getElementById) to locate elements by id.
* Wrap the HTML to a shorter line length (e.g. 80-100 characters or so) to make it easier to read in the GitHub UI and text editors and so that diffs and merges, etc. will be easier.

You can also use JS selectors to more elegantly find the data within an HTML element (e.g. "find the first child with class attribute 'notes'," etc). So you would have code for each exercise attribute you want to set, instead of looping over every child with a switch statement on the class name. (This is more of a style judgement.)

**Comment by cjerdonek** [comment]
PS - If you’re not already doing this, it could also help to maintain in the JavaScript a dictionary of the exercises mapping the short name or ID to the corresponding Exercise object. This will be useful for e.g. storing the “unlocks” info as data. The unlocks info could then be stored as e.g. a space-delimited attribute value of the div for that exercise.

**Comment by teorth** [comment]
OK, I'm done for now; I've prefixed the id's and formatted some of the HTML (not the proofs though, as this would be rather tedious and I would expect them to be rarely edited by hand).  

I have an exerciseList array that could be used for mapping ids to exercises if need be, but at present there isn't a need for it, so I haven't bothered to code a lookup routine yet.

Using a selector would indeed be more elegant, but it ain't broken right now, so I'm not fixing it.

**Comment by cjerdonek** [comment]
FYI, I added initial support for also storing the "unlockedBy" info in the HTML, and did this for the first couple exercises as an example.
